### ISSUE TITLE
Rendering without options/local variables doesn't work in Express 4

### ISSUE THREAD

**Issue by qazs** [tj/consolidate.js#149]
I'm using Express 4. 
This doesn't work:

```
cons.swig('views/index.html', function(err, html){
 ...
});
```

This works:

```
cons.swig('views/index.html', {}, function(err, html){
 ...
});
```

**Comment by x-yuri** [comment]
Oh, the issue already exists... Let me add my 5 cents:

> Or without options / local variables:
> 
> ```js
> var cons = require('consolidate');
> cons.swig('views/page.html', function(err, html){
>   if (err) throw err;
>   console.log(html);
> });
> ```

It doesn't work this way:

`1.sh`:

```sh
#!/bin/sh
set -eux
rm -rf node_modules package*
echo {} > package.json
npm install consolidate@"$1" swig
echo '
    1.txt
' > 1.txt
echo '
    var cons = require("consolidate");
    let args = ["1.txt"];
    if (process.argv[2] == "options")
        args.push({});
    args.push(function(err, res) {
        console.log(res);
    });
    cons.swig.apply(cons, args);
' > 1.js
node 1.js "$2"
```

```
$ docker run --rm -it -v $PWD/1.sh:/1.sh node:12-alpine3.11 ./1.sh 0.15.x options
...
+ echo '
    var cons = require("consolidate");
    let args = ["1.txt"];
    if (process.argv[2] == "options")
        args.push({});
    args.push(function(err, res) {
        console.log(res);
    });
    cons.swig.apply(cons, args);
'
+ node 1.js options

    1.txt
```
^ output

```
$ docker run --rm -it -v $PWD/1.sh:/1.sh node:12-alpine3.11 ./1.sh 0.15.x -
...
+ node 1.js -
```
^ no output
```
$ docker run --rm -it -v $PWD/1.sh:/1.sh node:12-alpine3.11 ./1.sh 0.1.0 -
...
+ node 1.js -
/node_modules/consolidate/lib/consolidate.js:97
      fn(err);
      ^

TypeError: fn is not a function
    at /node_modules/consolidate/lib/consolidate.js:97:7
    at /node_modules/consolidate/lib/consolidate.js:71:5
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```
^ error

Looking at the [point in time][1] where it was added, it doesn't look like it [ever worked][2]. I believe either the `README.md` or the code is to be fixed.

[1]: https://github.com/tj/consolidate.js/commit/d8c78e1
[2]: https://github.com/tj/consolidate.js/blob/d8c78e103c53daf5fa2bddf5e7fb011610140a95/lib/consolidate.js#L39-L51
