### ISSUE TITLE
Underscore reference error when using consolidate

### ISSUE THREAD

**Issue by bretcj7** [tj/consolidate.js#180]
Not sure on why this is failing, but here is my setup:

npm install -g consolidate   // success
npm install -g underscore   // success

-----app.js------
var cons = require('consolidate');
app.engine('html', cons.underscore);
app.set('view engine', 'html');

No errors in the startup of node, but when hitting my localhost:3000 it spews this error below.

ReferenceError: address is not defined
    at eval (eval at &lt;anonymous&gt; (/usr/local/yo_express/node_modules/underscore/underscore.js:1329:20), &lt;anonymous&gt;:5:2)
    at template (/usr/local/yo_express/node_modules/underscore/underscore.js:1336:21)
    at Function.exports.underscore.render (/usr/local/yo_express/node_modules/consolidate/lib/consolidate.js:517:14)
    at /usr/local/yo_express/node_modules/consolidate/lib/consolidate.js:146:25
    at /usr/local/yo_express/node_modules/consolidate/lib/consolidate.js:99:5
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)

**Comment by bretcj7** [comment]
The problem was in my route i had setup, no issue.  Closing.
