### ISSUE TITLE
Can't set headers after they are sent

### ISSUE THREAD

**Issue by tbergeron** [tj/consolidate.js#25]
Hi!

I'm always receiving this headers error when using consolidate with handlebars:

```
Error: Can't set headers after they are sent.
    at ServerResponse.<anonymous> (http.js:523:11)
    at ServerResponse.setHeader (/Users/tommybergeron/Desktop/ThinAir/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at ServerResponse.set (/Users/tommybergeron/Desktop/ThinAir/node_modules/express/lib/response.js:398:10)
    at ServerResponse.send (/Users/tommybergeron/Desktop/ThinAir/node_modules/express/lib/response.js:102:10)
    at /Users/tommybergeron/Desktop/ThinAir/node_modules/express/lib/response.js:610:12
    at /Users/tommybergeron/Desktop/ThinAir/node_modules/consolidate/lib/consolidate.js:310:7
    at /Users/tommybergeron/Desktop/ThinAir/node_modules/consolidate/lib/consolidate.js:71:5
    at [object Object].<anonymous> (fs.js:115:5)
    at [object Object].emit (events.js:64:17)
    at afterRead (fs.js:1117:12)
```

I didn't looked at the code yet, but I'll try to find out what happening. I just wanted to point it out to you :-)

Thanks!

**Comment by doowb** [comment]
Closing due to age.

It seems like this would be an express issue anyway.
