### ISSUE TITLE
Cannot find module 'consolidate'

### ISSUE THREAD

**Issue by onbetelgeuse** [tj/consolidate.js#257]
node -v : v4.6.0
npm -v: 2.15.9 

var cons = require('consolidate');

return the following error :

Error: Cannot find module 'consolidate'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (F:\wwwroot\WeatherApp\server.js:2:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by bananaappletw** [comment]
@onbetelgeuse Did you install it?
Maybe run `npm install consolidate --save` then try again?

**Comment by colebearski** [comment]
Do what banana said.
